# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: gestao-servicos
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 852456     
      MYSQL_DATABASE: gestaoservicos
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  my-db: